### ISSUE TITLE
[pretix] Update pretix guide for v4.x.x 

### ISSUE THREAD

**Issue by tobimori** [Uberspace/lab#1054]
So it seems like the way to install pretix’ requirements, as described in the guide, is outdated. Also, you now need two separate daemons (which might take too much RAM for Uberspace?).

**Comment by SalocinHB** [comment]
Thanks for pointing this out, our pretix guide is indeed no longer usable. @ezzra could you have a look at this and see if you can adapt your guide to Pretix 4.x? Otherwise we need to remove the guide from the Uberspace lab.

**Comment by kbpdev** [comment]
QA-Thread at https://github.com/pretix/pretix/discussions/2345 describes status quo.

I'm eager to help with updating the guide asa. the installation works :)

**Comment by nicogramm** [comment]
I have a (seemingly, couldn't manage to break it yet) working setup for the current pretix version. It'll take me a couple of days but I'll try to update (basically completely rewrite :joy:) the guide :))

**Comment by logazer** [comment]
Hey @nicogramm, that would be very much appreciated. Even just a gist of the configuration for starters. I wanted to install pretix and couldn't find the guide in the lab, so I ended up searching for it in this repository and found this issue.

@SalocinHB I think generally it might be better to add a disclaimer to the guide or even just replace the content with a note about it being removed. Simply deleting it only causes confusion, as you end up in a 404 when you follow links or you start thinking you're blind because you know it existed before ( (as in my case).

**Comment by luto** [comment]
fixed :)
