### ISSUE TITLE
add a guide for prosody xmpp-server

### ISSUE THREAD

**Issue by fapsi** [Uberspace/lab#107]
Hey, I would love to see a guide for [prosody](https://prosody.im/). Since I've currently not enough time, I create this as a remainder (for me), but maybe someone else will already have a look at it.
One can learn from/adapt this [tutorial](https://github.com/alexh-name/plaintext.blog/blob/master/src/hosting/Uberspace/prosody.txt), but I think one should ask for permission before doing that and also credit it.

Requirements regarding the Guide:
- Prosody 0.10 (or trunk?) ([sources](https://prosody.im/nightly/)/[config](https://prosody.im/doc/configure))
- TLS-Only (including file transfer)
- [SQL-Integration](https://prosody.im/doc/modules/mod_storage_sql) (Messages/Users/etc.) 
- Group-Chat (config)
- File-Transfer (config)
- Using [Community-Modules](https://modules.prosody.im/index.html)
- (Auto-)Update-Mechanism (including lua-deps, community-modules)
- ... (TBC)

**Comment by SalocinHB** [comment]
Requires the ability to open ports in the firewall. Not (yet) possible on U7.

**Comment by fapsi** [comment]
Thanks for the ports-feature! As far as I see unfortunately also requires #334 since relevant clients(e.g. conversations) don't support web-sockets (https://github.com/siacs/Conversations/issues/1170) . Anyway I will share my version of the guide (temporary without tls) soon!

**Comment by taddydevil** [comment]
I see the guide was closed because its too complex to support. I had some problems too (connect to other servers failed because invalid ssl connection or so).
Im writing down a simple german [Installation Guide](https://blog.bastlerkarre.de/installation-jabber-xmpp-prosody-auf-uberspace-7/) on my blog with the following [client-to-server](https://xmpp.net/result.php?id=1469588) and [server-to-server](https://xmpp.net/result.php?id=1469590) report. [This plugins](https://compliance.conversations.im/server/bastlerkarre.de/) are active right now. Maybe we have a second chance to get the guide into the lab?

**Comment by SalocinHB** [comment]
@taddydevil Sure, if you open another PR, we'll have a look at it

**Comment by taddydevil** [comment]
Is it possible to use the web backends instead of the port opening? Especially for SRV-Records? My first attempt with the http upload for files failed. I think if its possible the guide should be much more easier.

**Comment by taddydevil** [comment]
can be closed

**Comment by luto** [comment]
https://lab.uberspace.de/guide_prosody.html
