### ISSUE TITLE
[nextcloud] Update script does not work properly with current version

### ISSUE THREAD

**Issue by Susticle** [Uberspace/lab#1187]
The update script found at https://lab.uberspace.de/guide_nextcloud.html#updates runs some database optimisations with occ commands.

With the current version (23.0.0) of Nextcloud the following message is given:

```
Nextcloud is in maintenance mode, hence the database isn't accessible.
Cannot perform any command except 'maintenance:mode --off'
```

I think for newer versions it's necessary to remove the following lines from the update script:

```
## re-enable maintenance mode for occ commands
php ~/html/occ maintenance:mode --on
```

```
php ~/html/occ maintenance:mode --off
```

**Comment by escuco** [comment]
I can confirm the issue mentioned by @Susticle :

I've updated nextcloud from 22.2.2 to 22.2.3 -> no problems with the maintenance mode in the update script, like all updates I've done before.
After that I tried the update from 2.2.3 to 23.0.0 -> the script throws out the mentioned errors, even the update doesn't work.

I've updated nextcloud manually:
 
`.php ./occ upgrade`

and the update worked fine.

Then I tried the [update and optimization script from the documentation](https://lab.uberspace.de/guide_nextcloud.html?highlight=nextcloud#updates) without the maintenance mode and all remaining commands worked well.

**Comment by EV21** [comment]
Hi, 
I also noticed these messages, but since the log shows all database commands being executed, I just ignored the warnings. 
As of my knowledge (as documented) the maintenance mode only prevents user log-in and other server operations.
![grafik](https://user-images.githubusercontent.com/8345730/151186310-6b0ba082-3691-4c59-8ec9-eb4ff182e326.png)

I did some research and it looks like we actually don't need to activate the maintenance mode in this case. It is recommended while creating or restoring backups or doing the manual upgrades.

https://docs.nextcloud.com/server/latest/admin_manual/maintenance/upgrade.html#long-running-migration-steps

> From time to time we do some changes to the database layout that take a lot of time, but can be executed while Nextcloud **stays online**. Thus we moved them into a separate command that an administrator can execute on the CLI **without the need to lock the instance into maintenance mode** (at least for some of them).

--> As @Susticle suggested we should just remove these lines.
```
## re-enable maintenance mode for occ commands
php ~/html/occ maintenance:mode --on
```

---

@escuco I think I had a similar issue with that upgrade (it's been a few months). Running the script multiple (2x) times helped.
