### ISSUE TITLE
[ghost] removing guide

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1347]
Since version 5.21.0 the support for Mariadb was ultimately dropped by the ghost development community. Because of this, installing current releases of ghost is no longer possible on U7. Because this is a design decision by the ghost team and therefor there are no fixes in sight, we will remove the guide instantaneously.

**Comment by remarcable** [comment]
I was able to upgrade ghost from version `5.17.2` to version `5.25.0` and didn't experience any problems. I am a bit surprised the guide was removed because the `ghost` CLI explicitly states that support will only be removed from the next major version onward:
<img width="591" alt="Screenshot 2022-12-03 at 15 07 21" src="https://user-images.githubusercontent.com/11751444/205447594-a442261a-fdd9-4e4c-b8f8-5c40ea73351c.png">

I also couldn't find any mention about database changes in the [release notes](https://github.com/TryGhost/Ghost/releases/tag/v5.21.0). 

I suppose that in the long-term, after the next major release, the decision to remove the guide will make sense – but right now I don't understand what might have changed in version `5.21.0` that made it necessary to remove the guide.

**Comment by noave** [comment]
MariaDB is not the same as MySQL8. And MariaDB is no longer supported:

https://forum.ghost.org/t/post-only-error-request-not-understood-error-cannot-list-posts-could-not-understand-request/33768/2

But if you say you were successfull installing the latest ghost version, you can of course update the guide and create an PR :-)

https://github.com/Uberspace/lab/blob/1c371afc9761492d2b890500d6f8f71fae173f4b/source/guide_ghost.rst

**Comment by remarcable** [comment]
@noave Thank you very much! After about a month of using the latest ghost version on Uberspace, I can see that 99% of ghost is working. I noticed one minor problem when trying to view the post analytics where I get an error. Everything else is working.

All in all, I expect more to break in future versions.
