### ISSUE TITLE
[code-server] check for new nodejs version compatibility

### ISSUE THREAD

**Issue by noave** [Uberspace/lab#1594]
Nodejs 12 / 14 / 16 are EOL and wont be available on Uberspace any longer.

Check if this guide works with Nodejs18 or Nodejs20 and update it accordingly. Otherwise, if you cannot fix it with the new versions mark the guide as broken like it is described here: https://github.com/Uberspace/lab/blob/main/BROKEN_GUIDES.md 

_(This issue has been created automatically, the guide might already be up to date, in this case you can just comment and close the issue here)_

**Comment by muuuh** [comment]
I have the same issue here. Following version 4.17.0 - [https://github.com/coder/code-server/releases](https://github.com/coder/code-server/releases) - "_minimum glibc is now 2.28_"

My understanding ist, that
```
#ldd --version
ldd (GNU libc) 2.17
```

Searching on Twitter for previous questions about glibc - [https://nitter.net/ubernauten/search?f=tweets&q=glibc&since=&until=&near=](https://nitter.net/ubernauten/search?f=tweets&q=glibc&since=&until=&near=) - it seems that this cannot be fixed on the customer side.

I'll currently stick with the last known working version 4.17.0.
