### ISSUE TITLE
instructions how to set up collabora office

### ISSUE THREAD

**Issue by markum** [Uberspace/lab#160]
It would be great, if there were instructions how to set up [collabora office](https://www.collaboraoffice.com/collabora-online/) in Uberspace.

**Comment by coderkun** [comment]
Is it correct that that would require Docker? Maybe `udocker` can be used (see #159)?

**Comment by Si-Ke-Goe** [comment]
this would either require docker or java

**Comment by Kogoro** [comment]
I would be interested in a solution as well as collabora office is a key part of a nextcloud install.
I'm currently trying to use udocker but until now I couldn't get the docker file working.

@n0emis I could not find any reference to a normal java build. Do you have some pointers?

**Comment by microfx** [comment]
docker is not supported by uberspace... but there must be a way?

**Comment by beerisgood** [comment]
@luto 
@nazco 
@SalocinHB 

Any way to install that so we can boost Nextcloud?

I found this [guide](https://help.nextcloud.com/t/howto-install-collabora-online-on-ubuntu-16-04-without-docker/5014) to install it without Docker, but think it doesn't work with the restrictions on uberspce

**Comment by Kogoro** [comment]
With Nextcloud 18 aka Nextcloud Hub, collabora office is directly included as installable plugin.
Nevertheless, I do not know whether the machines at uberspace are powerful enough  or not. Maybe someone could test it and let us know.

**Comment by jorsn** [comment]
> With Nextcloud 18 aka Nextcloud Hub, collabora office is directly included as installable plugin.

Do you mean this: <https://apps.nextcloud.com/apps/richdocuments>? It's only a connector to a collabora instance. No collabora is installed.

However, there seems to be ONLYOFFICE as an app. It just doesn't seem to work far, according to my short trial and these issues:

* https://github.com/nextcloud/documentserver_community/issues/26
* https://github.com/nextcloud/documentserver_community/issues/61
* https://github.com/nextcloud/documentserver_community/issues/57

**Comment by Kogoro** [comment]
I was able to install the Community Document Server
(https://apps.nextcloud.com/apps/documentserver_community) successfully with increased timeout in the right file. This is surely a workaround, but for my local test instance why not. After downloading the app, you can simply change back the settings.

**Comment by beerisgood** [comment]
> 
> 
> I was able to install the Community Document Server
> (https://apps.nextcloud.com/apps/documentserver_community) successfully with increased timeout in the right file. This is surely a workaround, but for my local test instance why not. After downloading the app, you can simply change back the settings.

How did you install it?

**Comment by Kogoro** [comment]
You must increase the timeout in the client.php to an adequate time. A more deeper explanation is available under https://help.nextcloud.com/t/downloading-certain-apps-not-working/62603/11.
With the timeout increased, you should be able to download the app as usual.

**Comment by beerisgood** [comment]
> 
> 
> You must increase the timeout in the client.php to an adequate time. A more deeper explanation is available under https://help.nextcloud.com/t/downloading-certain-apps-not-working/62603/11.
> With the timeout increased, you should be able to download the app as usual.

Thanks. That did it!

Also the solution from that link is:

> I’ve solved the Problem by manually Setting the Value for
> "RequestOptions::TIMEOUT "
> to 120 or a higher value in the following file:
> “/path/to/nextcloud/lib/private/Http/Client/Client.php”

**Comment by jorsn** [comment]
My setup (#656) for the original *ONLYOFFICE DocumentServer using udocker* could also be an inspiration for *Collabora+udocker*. 

I use the DocumentServer because the performance of the NC app gets really bad with around 15+ simultaneous connections.

**Comment by JMoVS** [comment]
It seems now more than ever it would be really helpful if someone figures out either directly from nextcloud hub or with udocker on how to get the CODE server running. I am currently stuck with trying to even see logs which give me helpful error messages. Right now it just fails and i don't even know where to look for the logs.

**Comment by jorsn** [comment]
For anyone interested: #656 is now simplified to use web backends, *has no connection limit anymore and allows mobile editing.*

**Comment by jorsn** [comment]
# The Solution™

Shall I turn this into a guide?

So far I haven't tested the method using web backends. Serving collabora office should be possible in a subpath. Maybe an option has to be set, but don't think so.


## Prepare, Configure & Run

~~~
udocker pull collabora/code
create --name=collabora-code collabora/code
mkdir -p ~/etc/collabora && cp /etc/loolwsd/loolwsd.xml ~/etc/collabora
uberspace domain add lol.example.com
~~~

You can now edit ~/etc/collabora/loolwsd.xml to configure collabora office. You can also edit it to change configuration while the container is running. Another alternative is to set the options on the commandline, which is done in the script below.
You must set `security.capabilities=false`, because otherwise [capabilities(7)](https://man7.org/linux/man-pages/man7/capabilities.7.html) are requested which only root has. It is also advisable to set the `memproportion` (in percent) such that less than 1.5 GB are used, as this is the limit of an Uberspace.

### If you use an exposed port:

1. Run `uberspace port add` and refer to the port as `$PORT` in the following:
2. Run the following script:

~~~
#!/bin/sh

PORT=12345 # change this
lool_domain=lol.example.com
container=collabora-code

export DONT_GEN_SSL_CERT=1
export PROOT_NO_SECCOMP=1

# 'domain' is the domain of your WOPI host, e.g. your nextcloud.
udocker run -i -t --publish=$PORT:9980 --env="domain=nextcloud\\.example\\.com" \
        --env=username=admin --env=password=supersecretpassword --env=DONT_GEN_SSL_CERT=1 \
        --env='extra_params=--o:security.capabilities=false --o:memproportion=5.0 --o:per_document.max_concurrency=15 --o:logging=debug' \
        -v "$HOME"/etc/collabora/loolwsd.xml:/etc/loolwsd/loolwsd.xml \
        -v "$HOME"/.udocker/containers/$container/ROOT/start-libreoffice.sh:/sbin/start-libreoffice.sh \
        -v "$HOME"/etc/certificates/${lool_domain}.crt:/etc/loolwsd/cert.pem \
        -v "$HOME"/etc/certificates/${lool_domain}.key:/etc/loolwsd/key.pem \
        -v /etc/ssl/certs/ca-bundle.trust.crt:/etc/loolwsd/ca-chain.cert.pem \
        --user=101 \
        collabora-code
~~~

### If you use web backends:

1. Run `uberspace web backend set --http --port 9980 lol.example.com`
2. Run the above script, but remove the option `--publish=$PORT:9980` and add the option `--env=ssl.enable=false`. You can also remove the lines mapping the certificate and key.

## Test

Run on any machine connected to the internet (with curl+tls-support):

~~~
PORT=12345 curl -k https://lol.example.com:$PORT
~~~

**Comment by jorsn** [comment]
Currently, only exposed ports work. The instructions for using web backends don't – the collabora server seems to be not even accessed by the nextcloud. This is really strange.

**Comment by jorsn** [comment]
I wrote a guide (#768). It does not cover exposed ports, only web backends. Also, the post above contains some errors which I won't correct, since we have the guide. Especially, web backends are configured correctly *only in the guide*.
