### ISSUE TITLE
add guide for Baïkal

### ISSUE THREAD

**Issue by jonmz** [Uberspace/lab#188]
> Baïkal is a Cal and CardDAV server, based on sabre/dav, that includes an administrative interface for easy management.

http://sabre.io/baikal/

There's already a guide for U6: https://thomastaucher.at/pages/infcloud-in-conjunction-with-baikal/

It would be nice to have a guide for U7 as well.

**Comment by unamuno** [comment]
Maybe you want to migrate to nextcloud. It contains the same features and much more with a larger community.

**Comment by nichtmax** [comment]
@jonmz The last release [was 2016](https://github.com/sabre-io/Baikal/releases) and the installation requires PHP 5.5 according to [their docs](http://sabre.io/baikal/install/). 

Nextcloud has the same feature set and is much better maintainable.

**Comment by scouball** [comment]
There was just a [new version](https://github.com/sabre-io/Baikal/releases/tag/0.5.1) of baikal released yesterday with PHP 7.2. 

Since I don't need the cloud functions of nextcloud, baikal provides a simple cal- / carddav server without the overhead. If needed I could provide a guide for an installation.
