### ISSUE TITLE
cloudfront is used to serve assets

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#259]
I just opened https://lab.uberspace.de and everything was scrambled until I realized, that scripts and css is now loaded from external Amazon Cloudfront servers and I block all external requests by default for privacy reasons. Is that really necessary? I certainly do not mean the blocking, but youre storing of static files on external amazon servers and force visitors loading them from there.

I really appreciate Uberspace for your services and I always had the feeling of trust using them for a lot of projects and recommend them to a lot of other peoples. Also because I am deeply convinced of the importance of data protection and data security. And thats why I can recommend Uberspace without hesitation. But now, that little thing makes me hesitate.

Yes of course, Cloudfront is still far far away from embedding google analytics or whatever, Amazon might even say that they don't collect data with Cloudfront (do they say so?) and 98% of the users wont even notice it. But still, in my view right now there is quite a stain on the Uberlab page. 

And I feel quite bad supporting that with writing guides.

**Comment by nichtmax** [comment]
Hey @ezzra! Thanks for letting us know, looks like we mistakenly enabled [post processing and assert optimizations](https://www.netlify.com/blog/2015/10/31/control-your-post-processing/). The optimization feature has now been disabled, so the lab only loads content from `lab.uberspace.de` as well as our self hosted matomo/piwik instance.

Since this is a delicate topic you'll get a more wide-ranging answer later, I just wanted to let you know we already changed the configuration.

**Comment by luto** [comment]
After we collected opinions internally, here we go with our long answer:

Our lab, manual and status page are hosted on [netlify](https://www.netlify.com/). While we could of course build and host these static files ourselves, we decided to make use of an external service for a couple of reasons. The lab and manual are hosted there mainly for simplicity: building and maintaining a process to build/store/publish the sites ourselves takes time. Additionally, doing it neatly with [pull request previews](https://github.com/Uberspace/lab/pull/254) would certainly be out of scope for our rather small development team. Using an external tool enables us to spend time on other things like new U7 features and improves the experience for users writing or fixing guides. The status page is hosted externally for better availability in during the very outages it should inform our users about.

Netlify uses [digitalocean](https://www.digitalocean.com/) machines to serve the pages hosted there. You were seeing Amazon/Cloudfront because we mistakenly enabled the "post processing / assert optimizations" feature (public docs [here](https://www.netlify.com/blog/2015/10/31/control-your-post-processing/) and [here](https://www.netlify.com/blog/2017/02/15/how-to-shave-time-off-of-your-load-time-its-really-really-easy/), although it's rather thin). This apparently utilizes Amazon to process and host some of the content - mainly css, javascript and images. Thank you for bringing this to our attention.

The optimization feature has now been disabled for all three sites. So the lab only loads content from `lab.uberspace.de` as well as our self hosted matomo/piwik instance.

@ezzra Even though the sites are still hosted on netlify and thus still load content from external servers, we hope that you are now more comfortable with using and extending it in the future. Given that you wrote many great guides so far, it would be very sad for us to see you go.

Please let us know what you think! :)

**Comment by luto** [comment]
Closing this, as the original issue is resolved. Feel free to comment anyway.
