### ISSUE TITLE
Filtering mails with maildrop

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/lab#308]

**Comment by squarewf** [comment]
Filtering what, how? That's a tiny bit very generic, given that you can filter pretty much anything anywhere. For example, I got a somewhat sophisticated mailfilter setup running on U7 to replace the namespaces in U6 of yore, including sorting mails into folders based on sender and recipient, whitelisting and blacklisting recipients (for catchall), etc.

**Comment by nichtmax** [comment]
You're absolutely right. This issue is for rebuilding the namespace functionality that we removed with U7.

We'll implement filtering in general with sieve in the future.

**Comment by phlppk** [comment]
> * sorting mails into folders based on sender and recipient
> * whitelisting and blacklisting recipients based on lists of regular expressions (for a catchall-qmail-default)
> * supplement the X-Delivered-to header
> * flagging mails as "move to spam folder" or "outright delete", based on de

Would you mind sharing your filters? That sounds amazing.

**Comment by fooness** [comment]
Any news on this?

And, as @phlppk already asked, would @squarewf mind sharing their `.mailfilter` files?

Thank you!

**Comment by squarewf** [comment]
Oh, sorry, I didn't follow this anymore, after @nichtmax stated they will move away from maildropfilter in favour of sieve I thought my approach might be obsolete soon. However, that didn't happen (yet).

Here is my current .mailfilter. Please read carefully, and DO NOT COPY&PASTE, YOU WILL HAVE TO ADAPT IT TO YOUR PERSONAL NEEDS.
https://gist.github.com/squarewf/6bc060c06f43d6db353091d522e89001

**Comment by fooness** [comment]
Thank you @squarewf, that’s extremely helpful. Think I can figure out everything I need.

Basically I just want to achieve that `user-x@one-of-my-domains.tld` is delivered to one specific vmailmgr user/maildir and the same for `user-y@one-of-my-domains.tld` …

This should, thought, only happen for ONE one my domains and not for the others …

Would you mind sharing an example for an entry in `"$MAILFILTERDIR/good-recipients.txt"`?

Thank you!

**Comment by squarewf** [comment]
Oh, you don't need anything nearly as complicated as my .mailfilter then. In fact, that's one thing my .mailfilter _doesn't_ do: Sort into a different virtual mailbox.

This part
```
import EXT
import HOST
RECIPIENT="$EXT@$HOST"
```
will be useful for you to correctly determine the recipient (even if only in BCC). After that you can just create two `if` statements for those two addresses and set the $MAILDIR accordingly, then deliver the mail to that directory and be done. No need for elaborate and flexible rulesets.

**Comment by fooness** [comment]
Think I came up with a somewhat similar approach, basically merging the U6 mailfilter with the advice you just gave … let’s see if this works.

```
# set log file
logfile "$HOME/.mailfilter.log"

# set default mail directory
maildir="$HOME/Maildir"

# set environment variables and recipient
import EXT
import HOST
recipient="$EXT@$HOST"

# check if called from .qmail-user1 instead of .qmail
if ( $recipient == "user1@domain.tld" )
{
  # check if vmailmgr user $EXT exists
  checkmaildir=`dumpvuser $EXT | grep '^Directory' | awk '{ print $2 }'`
  if ( $checkmaildir )
  {
    # if yes, write log to their logfile
    logfile "$HOME/.mailfilter-$EXT.log"
    # if yes, deliver mail to their maildir
    maildir="$HOME/$checkmaildir"
  }
}

# check if called from .qmail-user2 instead of .qmail
if ( $recipient == "user1@domain.tld" )
{
  # check if vmailmgr user $EXT exists
  checkmaildir=`dumpvuser $EXT | grep '^Directory' | awk '{ print $2 }'`
  if ( $checkmaildir )
  {
    # if yes, write log to their logfile
    logfile "$HOME/.mailfilter-$EXT.log"
    # if yes, deliver mail to their maildir
    maildir="$HOME/$checkmaildir"
  }
}

# deliver everything that survived the filtering
to "$maildir"
```

**Comment by fooness** [comment]
@squarewf I’m not sure if `import HOST` and `$HOST` actually refer to the domain of the incoming email … fear it’s not as easy as I thought in the end.

(The problem is, now also `user1@one-of-my-other-domains.tld` is delivered to `user1` …)

**Comment by fooness** [comment]
```
lt, le, gt, ge, eq, ne - text comparison

expression1 lt expression2
expression1 le expression2
expression1 gt expression2
expression1 ge expression2
expression1 eq expression2
expression1 ne expression2
```

via: https://manpages.debian.org/testing/maildrop/mailfilter.5.en.html

**Comment by SalocinHB** [comment]
> Oh, sorry, I didn't follow this anymore, after @nichtmax stated they will move away from maildropfilter in favour of sieve I thought my approach might be obsolete soon.

tbh, I don't think we will be able to replace maildrop with Sieve in U7 – it's been there for too long now, people rely on it. Offering Sieve as an additional or alternative method (possibly as a future default) of filtering is still on the agenda, though.

**Comment by fooness** [comment]
> I don't think we will be able to replace maildrop with Sieve in U7 – it's been there for too long now, people rely on it.

Thank you for clarification.

> Offering Sieve as an additional or alternative method (possibly as a future default) of filtering is still on the agenda, though.

Never used Sieve before, but it sounds great.

Anyways, maybe I should go back to set up my U6 maildrop setup as described in https://wiki.uberspace.de/mail:maildrop#basiskonfiguration …

**Comment by keith24** [comment]
Is Uberspace actually planning on implementing Sieve at any point?  

I ask here because this is the top result when searching "uberspace sieve".  

Filtering is a pretty important feature.  I'd like to be able to filter out annoying automated emails without blocking an entire sender.  That is, after buying something on Amazon, I get a flood of emails like: 

- Your Amazon order has been confirmed
- The thing you bought on Amazon has been shipped
- The thing you bought on Amazon has been delivered
- Write a review for the thing you bought on Amazon

This happens with every single item I buy, and I get notifications for it, and have to delete them all by hand.  Drives me crazy!  Many sites let you turn off these notification emails, but many don't.  Implementing my own filters gives me more control of my inbox.  

I don't mind writing my own Maildrop rules... except I do actually.  It takes a long time to learn their language and write the script.  And any typo in my mailfilter can cause everything to break.  It's not user-friendly.  On the other hand, rainloop, roundcube, thunderbird (with plugin), and other mail clients have a built-in GUI for creating and modifying filters with Sieve.  I can't use filters with any of these clients, because Uberspace doesn't use Sieve. Likewise, I can't find any mail client that lets me edit my maildrop filters client-side.  So Sieve seems like a common feature for mailservers that is not yet supported by Uberspace.  

I'm putting this feature request here because some devs might monitor these issues.  If there's an official place to post feature requests, I can move my grievances there.  

Until then, this is my official +1 for a Sieve implementation for Uberspace mail.

**Comment by SalocinHB** [comment]
> Is Uberspace actually planning on implementing Sieve at any point?

Yes, but it will take time.

**Comment by rndph** [comment]
Looks like Sieve is there now:
https://manual.uberspace.de/en/changelog_archive.html#v7-7-7

**Comment by luto** [comment]
There is very basic sieve support now, yes. We'll expand it in future versions and add documentation.

**Comment by behrisch** [comment]
Just coming to the original topic of this ticket. Is anyone working on a maildrop guide for U7? Or should there be just a link to the old wiki https://wiki.uberspace.de/mail:maildrop somewhere? If you are currently looking for mail filtering in the U7 manual / lab you find only spam filtering but nothing about maildrop or sieve (at least I was not able to find it).

**Comment by luto** [comment]
The Sieve documentation will come soon, rendering maildrop obsolete.
