### ISSUE TITLE
mailman 3 updating

### ISSUE THREAD

**Issue by ezzra** [Uberspace/lab#362]
Currently there is no update strategy available within the guide. Actually its a problem that the guide states to remove the mailman_suite folder from the git versioned environment. I understand that the folder naming of the original repo is quite quirky, but that way it cannot be updated using git pull.

```
[isabell@stardust ~]$ git clone https://gitlab.com/mailman/mailman-suite.git
[isabell@stardust ~]$ mv mailman-suite/mailman-suite_project/ .
[isabell@stardust ~]$ rm -rf mailman-suite
[isabell@stardust ~]$ mv mailman-suite_project/ mailman-suite
[isabell@stardust ~]$
```

**Comment by rikroe** [comment]
I don't think that this is an issue. This git repo is only used to get the latest example _configuration_ for mailman (which you don't want to update). If you would do a git pull it would complain because you have changed your configuration files.

An update strategy would basically consinst of ``pip3.6 install {all_mailman_packages} --upgrade --user``. I'll add a short paragraph when removing the reverse proxy configuration.

**Comment by ezzra** [comment]
the current mailman guide says
> As Mailman 3 consists of multiple independent projects, there is no single RSS feed.

actually there is pypi version notification (with feeds) from libraries.io That might be better to use than regularly (not) checking for updates via pip command.

https://libraries.io/pypi/mailman/versions
https://libraries.io/pypi/mailman-hyperkitty/versions
https://libraries.io/pypi/postorius/versions
https://libraries.io/pypi/hyperkitty/versions
