### ISSUE TITLE
Guide for Web Key Directory

### ISSUE THREAD

**Issue by Marmo** [Uberspace/lab#473]
I'd like to share my notes how i set up a Web Key Directory on U6 (but I think there shouldn't be any differences for U7). I currently do not have time to translate this to ReST, but maybe someone else has.

https://spacekookie.de/blog/usable-gpg-with-wkd/
> [WKD] stands for "Web Key Directory" and is a standard for making a users public key available via their e-mail provider or server with the domain that corresponds to their e-mail address. There's several clients (such as Enigmail in Thunderbird) that will use this standard to automatically fetch a user's public key, when writing an e-mail to them.

See also https://wiki.gnupg.org/WKD .

# Create Directory Structure
```bash
mkdir -p ~/html/.well-known/openpgpkey/hu
touch ~/html/.well-known/openpgpkey/policy
```
~~Allow Directory Access:~~
DO NOT DO THIS:
~~echo "Options +Indexes" >> \~/html/.well-known/openpgpkey/hu/.htaccess~~
(can be a privacy issue, see Starkstromkonsuments comment below)

Instead use
```plaintext
## WEB KEY DIRECTORY ##
<IfModule mod_mime.c>
   ForceType application/octet-stream
   Header always set Access-Control-Allow-Origin "*"
</IfModule>
```
in `~/html/.well-known/openpgpkey/hu/.htaccess`.

# Calculate WKD-Hash of Mailuser
Take the prefix of your e-mail address (i.e. in `isabell@stardust.uberspace.de`, this would be `isabell`), hash it with SHA-1 and then encode the output with z-base-32.

You can use https://cryptii.com/pipes/z-base-32 for that (add a hash-block with SHA-1 before the z.base-32-block).
* E-Mail: isabell@startdust.uberspace.de
* Mailuser: isabell
* WKD-Hash: mmuhurigesr7z8hzf6sh5cmfsnmiiyyr

Alternatively you can invoke gpg with the option --with-wkd-hash on the machine where your keys reside:
```bash
gpg --with-wkd-hash --list-public-keys "isabell@stardust.uberspace.de"
[...]
      0123456789ABCDEF0123456789ABCDEF01234567
uid        [uneingeschränkt] Isabell <sabell@stardust.uberspace.de>
           mmuhurigesr7z8hzf6sh5cmfsnmiiyyr@stardust.uberspace.de
```

# Exporting and storing public GPG key

Export the **binary** Version of your public key into a file named as the WKD-hash calculated before:
```bash
gpg --export 0123456789ABCDEF0123456789ABCDEF01234567 > mmuhurigesr7z8hzf6sh5cmfsnmiiyyr
scp mmuhurigesr7z8hzf6sh5cmfsnmiiyyr isabell@stardust.uberspace.de:/home/isabell/html/.well-known/openpgpkey/hu
```

# Test
```bash
env GNUPGHOME=$(mktemp -d) gpg --locate-keys isabell@stardust.uberspace.de
```

**Comment by Starkstromkonsument** [comment]
Hi, I implemented this for my domain on my uberspace and I want to provide some additional hints:

- IMHO the `Options +Indexes` in .htaccess should NOT be set. It is not necessary and it reveals the number of emailadresses (and their hashes) in the WKD (this can be a privacy issue). The docs on https://wiki.gnupg.org/WKDHosting explicitly point out the following warning: **Make sure that there is no automatic directory listing**

- Add this to the `.htaccess` to set the correct headers:

```apache
## WEB KEY DIRECTORY ##
<IfModule mod_mime.c>
   ForceType application/octet-stream
   Header always set Access-Control-Allow-Origin "*"
</IfModule>
```

- The "advanced" method seems to be queried in front of the "direct" method by clients. If the subdomain openpgpkey resolves to a valid IP but the host at this IP does not provide the WKD (e.g. because of a wildcard in the DNS-Records), the WKD-lookup may fail.

- I therefore implemented the "advanced" method and the "direct" method:

```bash
# create the subdomain in your uberspace
uberspace web domain add openpgpkey.stardust.uberspace.de

# Create the directory structure for the "advanced" method:
# You must create a DNS-Record for openpgpkey.stardust.uberspace.de at your DNS-Hoster (it can be a CNAME to stardust.uberspace.de)!
cd /var/www/virtual/isabell/
mkdir -p openpgpkey.stardust.uberspace.de/.well-known/openpgpkey/stardust.uberspace.de/hu/
touch openpgpkey.stardust.uberspace.de/.well-known/openpgpkey/stardust.uberspace.de/hu/policy

# Create the directory structure for the "direct" method:
cd ~/
mkdir -p html/.well-known/openpgpkey
ln -s /var/www/virtual/isabell/openpgpkey.stardust.uberspace.de/.well-known/openpgpkey/stardust.uberspace.de/hu/ html/.well-known/openpgpkey/

# Create another symlink for lazy people like me to facilitate uploading keys via scp:
ln -s /var/www/virtual/isabell/
/openpgpkey.stardust.uberspace.de/.well-known/openpgpkey/stardust.uberspace.de/hu/ ./

# Upload keys:
scp mmuhurigesr7z8hzf6sh5cmfsnmiiyyr isabell@stardust.uberspace.de:hu/

# take a look at the directory structure
[isabell@startdust ~]$ tree -a hu
hu
├── .htaccess
├── policy
└── mmuhurigesr7z8hzf6sh5cmfsnmiiyyr
```
- The original docs: https://metacode.biz/openpgp/web-key-directory

- Another tutorial: https://www.kuketz-blog.de/gnupg-web-key-directory-wkd-einrichten/

- Testing tool: https://metacode.biz/openpgp/web-key-directory

I don't know anything about sphinx an the process how to write a lab-page yet. So this is all I can contribute at this moment.

Regards, Alex

**Comment by Starkstromkonsument** [comment]
I gave it a try today, but i can't get sphinx to work on my machine to test it :-(

```
$ make html
Sphinx v3.0.3 in Verwendung

Extension error:
Could not import extension authorship (exception: No module named 'authorship')
Makefile:23: recipe for target 'html' failed
make: *** [html] Error 2
```
Does anybody have a hint for me?

**Comment by Starkstromkonsument** [comment]
I'm sorry for the noise ... I'm new to github and sphinx.
