### ISSUE TITLE
feedback to mailman 3 guide

### ISSUE THREAD

**Issue by nichtmax** [Uberspace/lab#535]
> 1) Die verwendeten Versionen könnten prominenter platziert werden. In meinem U7 war ein Django > 3.0 installiert, dem das Modul django.utils.six fehlt (https://docs.djangoproject.com/en/3.0/releases/3.0/#s-removed-private-python-2-compatibility-apis), was zu Fehlermeldungen führte. Geholfen hat, mit "pip3 install --upgrade 'Django==2.1.8' --user" explizit die am Ende des Tutorials genannte Version zu setzen.
> 
> 2) Nach dem Daemonisieren des Mailman Core (https://lab.uberspace.de/guide_mailman-3.html#daemonizing-mailman-core) meldet "supervisorctl reread" nicht "SERVICE: available" sondern "mailman3: available". Natürlich auch bei den übrigen Meldungen.
> 
> 3) Da wir geschlossene Listen betreiben, soll sich niemand in Postorius registrieren können. Leider hab ich dazu keine Einstellung gefunden, so dass es auf ein "route = .* basicauth:Mailman 3,xxx:yyy" in der ~/uwsgi/apps-enabled/mailman-suite.ini hinauslief, um den Zugang bereits auf dieser Ebene zu beschränken. Womöglich wäre dieser Ansatz von allgemeinem Interesse?
> 
> 4) Bei den grundlegenden Einstellungen (https://lab.uberspace.de/guide_mailman-3.html#configure-mailman-core) für die ~/var/etc/mailman.cfg könnte in der section [mailman] ergänzt werden: "site_owner: isabell@uber.space" - Wenn man beim ersten Testen (Einrichten von Moderatoren, Hinzufügen von Subscribern) Mails vom voreingestellten changeme@example.com bekommt, ist das befremdlich. Andererseits eine gute Gelegenheit, den Leser in die ja auch verlinkten Original-Docs zu schicken. ;)
> 
> 5) Die Anleitung beschreibt das Setzen des Backends für "/". Dür mich war "/mailman" passender. Daher hatte ich das Backend an dieser Stelle eingehakt und in der "~/mailman-suite/urls.py" angepasst:
> 
> urlpatterns = [
>   url(r'^mailman/', include([
>   ... (Original-Inhalt) ...
>   ])),
> ]
> 
> Dadurch ist das Django-Admin-Interface nun auch unter /mailman/admin angesiedelt, aber das stört in unserem Fall nicht.

**Comment by jonmz** [comment]
Regarding the Django version: The problem seems to be the `haystack` module which tries to import `python_2_unicode_compatible` from Django which is no longer available in Django 3. `haystack` is used by the `hyperkitty` component of Mailman, and `hyperkitty` explicitly has "Django>=1.11,<2.3" as requirements, so in theory, no installation/upgrade to Django 3 should happen, so I suspect this not as a bug in the guide but as a bug in pip, leading to a set of modules that does effectively _not_ fulfill all constraints given. Until that is fixed, I suggest to follow the user's advice to explicitly install a recent Django 2 version.

**Comment by chgieseler** [comment]
I ran into the very same django version issue last night. With your last sentence said. What is the next suggested action? Shall i just file a pull request with a patch that adds a hint to the first bullet point nichtmax has mentioned above?

**Comment by jonmz** [comment]
> I ran into the very same django version issue last night. With your last sentence said. What is the next suggested action? Shall i just file a pull request with a patch that adds a hint to the first bullet point nichtmax has mentioned above?

That would be cool. I also observed that switching `postorius` and `hyperkitty` in the `pip` call (so that `hyperkitty` comes first) also actually helps, so maybe if you can reproduce that we could take that road. I'm not _too_ familiar with `pip`s dependency resolving system so I'm not sure if this is a bug or intended behaviour.

**Comment by flootr** [comment]
I experienced the same problem and can confirm that switching `postorius` with `hyperkitty` in the `pip` call does indeed fix the aforementioned problem 👍

**Comment by pheraph** [comment]
Switching `postorius` and `hyperkitty` did the trick for me, too. As I followed the lab guide I had to uninstall both modules (`pip3.6 uninstall postorius hyperkitty`) before I was able to re-install them in the correct order: https://github.com/Uberspace/lab/pull/561
