### ISSUE TITLE
How to handle .htaccess of Nextcloud

### ISSUE THREAD

**Issue by Ryuno-Ki** [Uberspace/lab#798]
This week, I finally migrated from U6 to U7.

Since my old Nextcloud setup was … aged, I decided to start from scratch using Nextcloud 20 (latest).
I discovered https://github.com/Uberspace/lab/blob/0df9a9d8dd77bde546e01135a07ea7ebf95b43f5/source/guide_nextcloud.rst

Nextcloud comes with [instructions on how to configure Apache](https://docs.nextcloud.com/server/20/admin_manual/installation/source_installation.html#apache-web-server-configuration).

Since Uberspace is a Shared Hosting provider, not all rules would apply (I guess - at least it was so in U6).

**Could a section be added to the guide?**

So far, I configured the service discovery URLs („.well-known” URLs), but would like to harden my installation.
When logged in as admin, you can run a check from the Web UI and tweak [php.ini as described](https://lab.uberspace.de/guide_nextcloud.html#php-memory).

**Comment by luto** [comment]
The guide was rewritten since this issue was opened. Please open another, updated on, if this is still relevant.

**Comment by Ryuno-Ki** [comment]
Thanks!

**Comment by udaemon** [comment]
hi,
i would like to take this up again since recently messages pop up within NC stating that the webserver is not properly set in order to resolve
/.well-known/webfinger
/.well-known/nodeinfo
/.well-known/caldav
/.well-known/carddav

so far, i was able to find a solution because every guide refers to a certain apache base which is not given like that at uberspace - resp. I don't understand to translate it.
can somebody help?
thanks!
:)
