### ISSUE TITLE
nextcloud recommends using PHP 7.4 

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/lab#994]
https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

**Comment by EV21** [comment]
Why?
That linked documentation page is outdated, it misses php 8.0  - With Nextcloud 21 they have done many performance optimisations with php 8.0 features

> PHP 8 compatibility can bring an additional performance boost to Nextcloud deployments.

Even if we don't (yet) use the Performance-Backend there are improvements and php 8.0 is fully supported for NC21.
https://nextcloud.com/blog/nextcloud-hub-21-out-with-up-to-10x-better-performance-whiteboard-and-more-collaboration-features/

You may also have a look at https://youtu.be/2IxvNyCAEio?t=876 where some performance improvements are explained with "php 8.0 preload and JIT"

**Comment by luto** [comment]
The documentation does not mention 8.0, their Dockerfile uses 7.4, and their automated tests do not test 8.0. It's clear that they are experimenting with and working towards to 8.0, but that's not what prime support looks like. Since we try to stay as close to the official docs as possible to all tools: back to 7.4 it is.
